version: '3.9'

services:

  redpanda:
    image: redpandadata/redpanda:v23.3.11
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  postgres:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_DB:       focuslens
      POSTGRES_USER:     fl_user
      POSTGRES_PASSWORD: fl_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  redpanda_data:
  pg_data: