apiVersion: v1
kind: Secret
metadata:
  name: focuslens-secrets
  namespace: focuslens
type: Opaque
stringData:
  POSTGRES_USER:     "fl_user"
  POSTGRES_PASSWORD: "fl_pass"
  POSTGRES_DB:       "focuslens"